"""blueprint.py — Full CBSE Class 10 Blueprint 2024-25 + 8-year historical appearance data."""

# ── CBSE Blueprint ────────────────────────────────────────────────────────────
BLUEPRINT = {
    "science": {
        "total_marks": 80, "duration": "3 hours",
        "units": {
            "Chemical Substances":  {"marks": 25, "chapters": ["Chemical Reactions and Equations","Acids, Bases and Salts","Metals and Non-metals","Carbon and Its Compounds"]},
            "World of Living":      {"marks": 25, "chapters": ["Life Processes","Control and Coordination","How do Organisms Reproduce?","Heredity"]},
            "Natural Phenomena":    {"marks": 12, "chapters": ["Light - Reflection and Refraction","The Human Eye and the Colourful World"]},
            "Effects of Current":   {"marks": 13, "chapters": ["Electricity","Magnetic Effects of Electric Current"]},
            "Natural Resources":    {"marks": 5,  "chapters": ["Our Environment","Management of Natural Resources"]},
        },
        "chapters": {
            "Chemical Reactions and Equations":       {"unit":"Chemical Substances",  "weight":7,  "ncert_ex":25,"exemplar":18,"deleted":False,"key_topics":["types of reactions","oxidation reduction","redox","balancing equations","corrosion","rancidity"]},
            "Acids, Bases and Salts":                 {"unit":"Chemical Substances",  "weight":8,  "ncert_ex":28,"exemplar":22,"deleted":False,"key_topics":["pH scale","neutralisation","salts","baking soda","washing soda","plaster of paris","bleaching powder"]},
            "Metals and Non-metals":                  {"unit":"Chemical Substances",  "weight":6,  "ncert_ex":22,"exemplar":20,"deleted":False,"key_topics":["reactivity series","extraction","ionic compounds","corrosion","alloys"]},
            "Carbon and Its Compounds":               {"unit":"Chemical Substances",  "weight":4,  "ncert_ex":20,"exemplar":16,"deleted":False,"key_topics":["covalent bonds","homologous series","ethanol","ethanoic acid","soaps detergents","isomers"]},
            "Life Processes":                         {"unit":"World of Living",      "weight":10, "ncert_ex":30,"exemplar":24,"deleted":False,"key_topics":["nutrition photosynthesis","respiration","transportation","excretion","osmoregulation"]},
            "Control and Coordination":               {"unit":"World of Living",      "weight":7,  "ncert_ex":18,"exemplar":15,"deleted":False,"key_topics":["nervous system","reflex arc","brain","hormones","endocrine system"]},
            "How do Organisms Reproduce?":            {"unit":"World of Living",      "weight":5,  "ncert_ex":15,"exemplar":12,"deleted":False,"key_topics":["asexual reproduction","sexual reproduction","fertilisation","contraception","STDs"]},
            "Heredity":                               {"unit":"World of Living",      "weight":3,  "ncert_ex":12,"exemplar":10,"deleted":False,"key_topics":["Mendel","dominant recessive","sex determination","evolution","speciation"]},
            "Light - Reflection and Refraction":      {"unit":"Natural Phenomena",    "weight":7,  "ncert_ex":20,"exemplar":18,"deleted":False,"key_topics":["mirrors","lenses","ray diagrams","refraction","lens formula","mirror formula","power of lens"]},
            "The Human Eye and the Colourful World":  {"unit":"Natural Phenomena",    "weight":5,  "ncert_ex":14,"exemplar":12,"deleted":False,"key_topics":["defects of vision","dispersion","scattering","rainbow","tyndall effect"]},
            "Electricity":                            {"unit":"Effects of Current",   "weight":7,  "ncert_ex":22,"exemplar":20,"deleted":False,"key_topics":["Ohm's law","resistance","series parallel","heating effect","Joule's law","power","domestic wiring"]},
            "Magnetic Effects of Electric Current":   {"unit":"Effects of Current",   "weight":6,  "ncert_ex":16,"exemplar":14,"deleted":False,"key_topics":["magnetic field","Fleming rules","electromagnetic induction","AC DC","generator motor","fuse"]},
            "Our Environment":                        {"unit":"Natural Resources",    "weight":3,  "ncert_ex":10,"exemplar":8, "deleted":False,"key_topics":["food chains","ecosystem","ozone","biodegradable","waste management"]},
            "Management of Natural Resources":        {"unit":"Natural Resources",    "weight":2,  "ncert_ex":8, "exemplar":6, "deleted":False,"key_topics":["conservation","forests","water harvesting","coal petroleum","sustainable development"]},
        },
        "qtypes": {"MCQ":{"m":1,"n":20},"SA1":{"m":2,"n":6},"SA2":{"m":3,"n":7},"LA":{"m":5,"n":3}},
    },

    "math": {
        "total_marks": 80, "duration": "3 hours",
        "units": {
            "Number Systems":             {"marks":6,  "chapters":["Real Numbers"]},
            "Algebra":                    {"marks":20, "chapters":["Polynomials","Pair of Linear Equations in Two Variables","Quadratic Equations","Arithmetic Progressions"]},
            "Coordinate Geometry":        {"marks":6,  "chapters":["Coordinate Geometry"]},
            "Geometry":                   {"marks":15, "chapters":["Triangles","Circles"]},
            "Trigonometry":               {"marks":12, "chapters":["Introduction to Trigonometry","Some Applications of Trigonometry"]},
            "Mensuration":                {"marks":10, "chapters":["Areas Related to Circles","Surface Areas and Volumes"]},
            "Statistics & Probability":   {"marks":11, "chapters":["Statistics","Probability"]},
        },
        "chapters": {
            "Real Numbers":                               {"unit":"Number Systems",           "weight":6,  "ncert_ex":18,"exemplar":15,"deleted":False,"key_topics":["Euclid's algorithm","HCF LCM","irrational numbers","decimal expansions","fundamental theorem"]},
            "Polynomials":                                {"unit":"Algebra",                  "weight":5,  "ncert_ex":15,"exemplar":12,"deleted":False,"key_topics":["zeroes","relationship coefficients","division algorithm","geometric meaning"]},
            "Pair of Linear Equations in Two Variables":  {"unit":"Algebra",                  "weight":6,  "ncert_ex":22,"exemplar":18,"deleted":False,"key_topics":["graphical method","substitution","elimination","cross-multiplication","word problems"]},
            "Quadratic Equations":                        {"unit":"Algebra",                  "weight":5,  "ncert_ex":18,"exemplar":15,"deleted":False,"key_topics":["factorisation","completing square","quadratic formula","discriminant","nature of roots","word problems"]},
            "Arithmetic Progressions":                    {"unit":"Algebra",                  "weight":4,  "ncert_ex":20,"exemplar":16,"deleted":False,"key_topics":["nth term","sum of n terms","word problems","finding AP"]},
            "Coordinate Geometry":                        {"unit":"Coordinate Geometry",      "weight":6,  "ncert_ex":16,"exemplar":14,"deleted":False,"key_topics":["distance formula","section formula","midpoint","area of triangle","collinearity"]},
            "Triangles":                                  {"unit":"Geometry",                 "weight":7,  "ncert_ex":25,"exemplar":22,"deleted":False,"key_topics":["similarity","BPT","AA SAS SSS criteria","areas","Pythagoras theorem","converse"]},
            "Circles":                                    {"unit":"Geometry",                 "weight":5,  "ncert_ex":14,"exemplar":12,"deleted":False,"key_topics":["tangent","number of tangents","tangent perpendicular","lengths from external point"]},
            "Introduction to Trigonometry":               {"unit":"Trigonometry",             "weight":6,  "ncert_ex":18,"exemplar":16,"deleted":False,"key_topics":["ratios","identities","trigonometric tables","complementary angles","sin cos tan"]},
            "Some Applications of Trigonometry":          {"unit":"Trigonometry",             "weight":6,  "ncert_ex":10,"exemplar":8, "deleted":False,"key_topics":["heights distances","angle of elevation depression","word problems"]},
            "Areas Related to Circles":                   {"unit":"Mensuration",              "weight":4,  "ncert_ex":12,"exemplar":10,"deleted":False,"key_topics":["sector area","segment area","perimeter","combination figures"]},
            "Surface Areas and Volumes":                  {"unit":"Mensuration",              "weight":6,  "ncert_ex":16,"exemplar":14,"deleted":False,"key_topics":["combination solids","frustum","conversion of solids","word problems"]},
            "Statistics":                                 {"unit":"Statistics & Probability", "weight":6,  "ncert_ex":18,"exemplar":15,"deleted":False,"key_topics":["mean","median","mode","grouped data","ogive","cumulative frequency"]},
            "Probability":                                {"unit":"Statistics & Probability", "weight":5,  "ncert_ex":14,"exemplar":12,"deleted":False,"key_topics":["classical probability","complementary events","cards dice coins","word problems"]},
        },
        "qtypes": {"MCQ":{"m":1,"n":20},"SA1":{"m":2,"n":5},"SA2":{"m":3,"n":6},"LA":{"m":4,"n":4},"CASE":{"m":4,"n":2}},
    },

    "social_science": {
        "total_marks": 80, "duration": "3 hours",
        "units": {
            "History":   {"marks":20, "chapters":["The Rise of Nationalism in Europe","Nationalism in India","The Making of a Global World","The Age of Industrialisation"]},
            "Geography": {"marks":20, "chapters":["Resources and Development","Forest and Wildlife Resources","Water Resources","Agriculture","Minerals and Energy Resources","Manufacturing Industries","Lifelines of National Economy"]},
            "Civics":    {"marks":20, "chapters":["Power Sharing","Federalism","Democracy and Diversity","Gender Religion and Caste","Popular Struggles and Movements","Political Parties","Outcomes of Democracy"]},
            "Economics": {"marks":20, "chapters":["Development","Sectors of the Indian Economy","Money and Credit","Globalisation and the Indian Economy","Consumer Rights"]},
        },
        "chapters": {
            "The Rise of Nationalism in Europe":       {"unit":"History",   "weight":5,  "ncert_ex":12,"exemplar":10,"deleted":False,"key_topics":["French Revolution","Napoleonic code","German unification","Italian unification","Balkans","nationalism symbols"]},
            "Nationalism in India":                    {"unit":"History",   "weight":8,  "ncert_ex":15,"exemplar":14,"deleted":False,"key_topics":["Non-cooperation movement","Civil disobedience","Salt March","Simon Commission","Gandhi","Rowlatt Act","Khilafat"]},
            "The Making of a Global World":            {"unit":"History",   "weight":4,  "ncert_ex":10,"exemplar":8, "deleted":False,"key_topics":["Silk routes","colonialism","Bretton Woods","Great Depression","post-WW2 economy"]},
            "The Age of Industrialisation":            {"unit":"History",   "weight":3,  "ncert_ex":9, "exemplar":7, "deleted":False,"key_topics":["proto-industrialisation","factories","cotton mills","labour","Manchester","Bombay"]},
            "Resources and Development":               {"unit":"Geography", "weight":5,  "ncert_ex":12,"exemplar":10,"deleted":False,"key_topics":["types of resources","resource planning","land degradation","soil conservation","soil types"]},
            "Forest and Wildlife Resources":           {"unit":"Geography", "weight":4,  "ncert_ex":10,"exemplar":8, "deleted":False,"key_topics":["flora fauna","reserved forests","conservation","biodiversity","chipko movement","JFM"]},
            "Water Resources":                         {"unit":"Geography", "weight":4,  "ncert_ex":10,"exemplar":8, "deleted":False,"key_topics":["multipurpose projects","rainwater harvesting","water scarcity","Narmada bachao","bamboo drip"]},
            "Agriculture":                             {"unit":"Geography", "weight":4,  "ncert_ex":11,"exemplar":9, "deleted":False,"key_topics":["cropping patterns","types of farming","green revolution","food security","kharif rabi","horticulture"]},
            "Minerals and Energy Resources":           {"unit":"Geography", "weight":3,  "ncert_ex":9, "exemplar":7, "deleted":False,"key_topics":["types of minerals","mining","energy resources","solar wind","thermal nuclear"]},
            "Manufacturing Industries":                {"unit":"Geography", "weight":3,  "ncert_ex":9, "exemplar":7, "deleted":False,"key_topics":["importance","agro-based industries","textile steel cement","industrial pollution","special economic zones"]},
            "Lifelines of National Economy":           {"unit":"Geography", "weight":2,  "ncert_ex":7, "exemplar":5, "deleted":False,"key_topics":["roadways railways","waterways","airways","pipelines","trade","tourism"]},
            "Power Sharing":                           {"unit":"Civics",    "weight":5,  "ncert_ex":10,"exemplar":9, "deleted":False,"key_topics":["Belgium Sri Lanka","horizontal vertical sharing","coalition","majoritarianism","prudential moral reasons"]},
            "Federalism":                              {"unit":"Civics",    "weight":5,  "ncert_ex":12,"exemplar":10,"deleted":False,"key_topics":["federal unitary","coming holding together","decentralisation","3-tier government","panchayati raj"]},
            "Democracy and Diversity":                 {"unit":"Civics",    "weight":3,  "ncert_ex":8, "exemplar":7, "deleted":False,"key_topics":["social divisions","Mexico Olympics 1968","Northern Ireland","factors affecting politics"]},
            "Gender Religion and Caste":               {"unit":"Civics",    "weight":4,  "ncert_ex":9, "exemplar":8, "deleted":False,"key_topics":["sexual division of labour","women's movement","communalism","caste and politics"]},
            "Popular Struggles and Movements":         {"unit":"Civics",    "weight":3,  "ncert_ex":8, "exemplar":6, "deleted":False,"key_topics":["Nepal movement","Bolivia water war","interest groups","pressure groups","movement types"]},
            "Political Parties":                       {"unit":"Civics",    "weight":2,  "ncert_ex":7, "exemplar":5, "deleted":False,"key_topics":["functions","types","national state parties","challenges","reforms"]},
            "Outcomes of Democracy":                   {"unit":"Civics",    "weight":2,  "ncert_ex":6, "exemplar":5, "deleted":False,"key_topics":["accountable legitimate","economic growth","inequality","dignity","evaluation"]},
            "Development":                             {"unit":"Economics", "weight":5,  "ncert_ex":10,"exemplar":9, "deleted":False,"key_topics":["national income","per capita income","HDI","Kerala vs Punjab","sustainability","goals of development"]},
            "Sectors of the Indian Economy":           {"unit":"Economics", "weight":5,  "ncert_ex":12,"exemplar":10,"deleted":False,"key_topics":["primary secondary tertiary","GDP","organised unorganised","NREGA","underemployment"]},
            "Money and Credit":                        {"unit":"Economics", "weight":5,  "ncert_ex":11,"exemplar":9, "deleted":False,"key_topics":["barter","modern forms of money","credit","formal informal sector","SHGs","RBI","collateral"]},
            "Globalisation and the Indian Economy":    {"unit":"Economics", "weight":5,  "ncert_ex":10,"exemplar":8, "deleted":False,"key_topics":["MNCs","liberalisation","WTO","fair trade","SEZ","impact on Indian industry"]},
            "Consumer Rights":                         {"unit":"Economics", "weight":2,  "ncert_ex":7, "exemplar":5, "deleted":False,"key_topics":["consumer protection act","COPRA","consumer courts","ISI Agmark","RTI","consumer movement"]},
        },
        "qtypes": {"MCQ":{"m":1,"n":20},"SA1":{"m":3,"n":5},"SA2":{"m":5,"n":4},"MAP":{"m":5,"n":1}},
        "map_work": {
            "history":   ["Peasant movements","Salt March locations","Industries 1850","Major ports pre-independence"],
            "geography": ["Dams and multipurpose projects","Power plants","Iron steel industries","Major ports airports","Cotton jute textile mills"],
        },
    },
}

# ── Historical Appearances (year → appeared or not) ───────────────────────────
HISTORY = {
    "science": {
        "Chemical Reactions and Equations":       [2024,2023,2022,2020,2019,2018,2017,2016],
        "Acids, Bases and Salts":                 [2024,2023,2022,2020,2019,2018,2017,2016],
        "Metals and Non-metals":                  [2024,2023,2022,2020,2019,2018,2017,2016],
        "Carbon and Its Compounds":               [2024,2023,2020,2019,2018,2016],
        "Life Processes":                         [2024,2023,2022,2020,2019,2018,2017,2016],
        "Control and Coordination":               [2024,2023,2022,2020,2019,2018,2017],
        "How do Organisms Reproduce?":            [2024,2023,2020,2019,2018,2016],
        "Heredity":                               [2024,2023,2022,2020,2019],
        "Light - Reflection and Refraction":      [2024,2023,2022,2020,2019,2018,2017,2016],
        "The Human Eye and the Colourful World":  [2024,2023,2022,2020,2019,2018],
        "Electricity":                            [2024,2023,2022,2020,2019,2018,2017,2016],
        "Magnetic Effects of Electric Current":   [2024,2023,2022,2020,2019,2018,2016],
        "Our Environment":                        [2024,2023,2020,2019,2017],
        "Management of Natural Resources":        [2023,2022,2019,2018],
    },
    "math": {
        "Real Numbers":                               [2024,2023,2022,2020,2019,2018,2017,2016],
        "Polynomials":                                [2024,2023,2022,2020,2019,2018,2017],
        "Pair of Linear Equations in Two Variables":  [2024,2023,2022,2020,2019,2018,2017,2016],
        "Quadratic Equations":                        [2024,2023,2022,2020,2019,2018,2017,2016],
        "Arithmetic Progressions":                    [2024,2023,2022,2020,2019,2018,2017],
        "Coordinate Geometry":                        [2024,2023,2022,2020,2019,2018,2017],
        "Triangles":                                  [2024,2023,2022,2020,2019,2018,2017,2016],
        "Circles":                                    [2024,2023,2022,2020,2019,2018],
        "Introduction to Trigonometry":               [2024,2023,2022,2020,2019,2018,2017,2016],
        "Some Applications of Trigonometry":          [2024,2023,2022,2020,2019,2018,2017],
        "Areas Related to Circles":                   [2024,2023,2022,2020,2019],
        "Surface Areas and Volumes":                  [2024,2023,2022,2020,2019,2018,2017],
        "Statistics":                                 [2024,2023,2022,2020,2019,2018,2017,2016],
        "Probability":                                [2024,2023,2022,2020,2019,2018,2017],
    },
    "social_science": {
        "Nationalism in India":                  [2024,2023,2022,2020,2019,2018,2017,2016],
        "The Rise of Nationalism in Europe":     [2024,2023,2022,2020,2019,2018,2017],
        "The Making of a Global World":          [2024,2023,2022,2020,2019,2018],
        "The Age of Industrialisation":          [2024,2023,2022,2020,2019],
        "Resources and Development":             [2024,2023,2022,2020,2019,2018,2017],
        "Water Resources":                       [2024,2023,2022,2020,2019,2018],
        "Agriculture":                           [2024,2023,2022,2020,2019,2018,2016],
        "Power Sharing":                         [2024,2023,2022,2020,2019,2018,2017,2016],
        "Federalism":                            [2024,2023,2022,2020,2019,2018,2017],
        "Democracy and Diversity":               [2024,2023,2022,2020,2019],
        "Gender Religion and Caste":             [2024,2023,2022,2020,2019,2018],
        "Development":                           [2024,2023,2022,2020,2019,2018,2017,2016],
        "Sectors of the Indian Economy":         [2024,2023,2022,2020,2019,2018],
        "Money and Credit":                      [2024,2023,2022,2020,2019,2018,2017],
        "Globalisation and the Indian Economy":  [2024,2023,2022,2020,2019,2018],
    },
}

# Chapters last seen in a specific year (for gap analysis)
LAST_SEEN = {
    "science": {
        "Carbon and Its Compounds":         2023,
        "Management of Natural Resources":  2023,
        "How do Organisms Reproduce?":      2023,
    },
    "math": {
        "Areas Related to Circles":         2023,
        "Circles":                          2024,
    },
    "social_science": {
        "The Age of Industrialisation":     2023,
        "Consumer Rights":                  2022,
        "Popular Struggles and Movements":  2022,
        "Manufacturing Industries":         2023,
        "Lifelines of National Economy":    2022,
    },
}
