import json
from pathlib import Path

def format_question(q):
    marks = q.get('marks', '?')
    qtype = q.get('type', '?')
    conf = q.get('confidence', '?')
    score = q.get('composite_score', 0.0)
    chap = q.get('chapter', '?')
    unit = q.get('unit', '?')
    ques = q.get('question', '?')
    scheme = q.get('scheme', '')
    reason = q.get('reason', '')
    signals = ", ".join(q.get('source_signals', []))
    
    md = f"### Q{q['rank']}. ({marks}M) — {qtype} | Confidence: {conf} | Score: {score:.3f}\n\n"
    md += f"**Chapter:** {chap} ({unit})\n\n"
    md += f"> {ques.replace('\\n', '\n> ')}\n\n"
    if scheme:
        md += f"**Marking Scheme:**\n{scheme}\n\n"
    md += f"**AI Reasoning:** {reason}\n"
    if signals:
        md += f"**Source Signals:** {signals}\n"
    md += "---\n\n"
    return md

def main():
    output = "# 🎯 CBSE Class 10 Board Exam 2026 Predictions\n\n"
    output += "Generated by **Gemini 2.5 Flash** using 15 years of exam intelligence, blueprint weights, and educator signals.\n\n"
    
    subjects = {
        "science": "Science (086)",
        "math": "Mathematics (041)",
        "social_science": "Social Science (087)"
    }
    
    for subj_key, subj_name in subjects.items():
        output += f"## 📘 {subj_name}\n\n"
        path = Path(f"{'sst' if subj_key == 'social_science' else subj_key}.json")
        if not path.exists():
            # Fallback to results.json if specific file not found
            path = Path("results.json")
            
        if path.exists():
            try:
                data = json.loads(path.read_text())
                # Handle different export structures
                if "predictions" in data:
                    qs = data["predictions"].get(subj_key, [])
                else:
                    # If the file only contains that subject's list
                    qs = data.get(subj_key, []) if isinstance(data, dict) else data
                
                if qs:
                    for q in qs:
                        output += format_question(q)
                else:
                    output += "*No predictions found for this subject.*\n\n"
            except Exception as e:
                output += f"*Error reading data: {e}*\n\n"
        else:
            output += f"*Data file {path} not found.*\n\n"
            
    Path("output.md").write_text(output)
    print("output.md generated successfully.")

if __name__ == "__main__":
    main()
